# Generated by Django 3.2.7 on 2021-09-10 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FW', 'Forward')], max_length=2)),
                ('totalPoints', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('defenders', models.ManyToManyField(related_name='df_teams', to='teams.Player')),
                ('forwards', models.ManyToManyField(related_name='fw_teams', to='teams.Player')),
                ('goalkeeper', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gk_teams', to='teams.player')),
                ('midfielders', models.ManyToManyField(related_name='mf_teams', to='teams.Player')),
            ],
        ),
    ]
