# Generated by Django 3.2.7 on 2021-09-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.CharField(default='poo', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.CharField(default='wee', max_length=100),
            preserve_default=False,
        ),
    ]
