# Generated by Django 3.2.7 on 2021-09-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='thumbnail',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
    ]
